services:
  ondare-nextjs:
    build:
      context: ondare-nextjs
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
    env_file:
      - ondare-nextjs/.env
